#!/bin/bash 
  
cd
rm -rf BTC-solo
git clone https://github.com/saengx/BTC-solo
cd ../etc/src-miner/set-miner
cp -r online.json offline.json /../root/BTC-solo/src-miner/set-miner
cd
cd ../etc
rm -rf src-miner 
cd
cd ../bin
rm -rf edit run
cd
cd BTC-solo
chmod +x setupdate.sh
sh setupdate.sh
